trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd edusyncfrontend
    npm install
    npm run build
  displayName: 'Build React App'

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'edusyncfrontend'                      # Where your React source code is
    output_location: 'build'                             # React build output
    azure_static_web_apps_api_token: $(deployment_token) # ✅ Define this secret in DevOps
    sku: 'Free'
    is_static_export: true
  displayName: 'Deploy to Azure Static Web App'
